builder:
  track: dev

labels:
  app: estafette-ci-manifest
  team: estafette-team
  language: golang

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending
    when:
      server == 'estafette'

  build:
    image: golang:1.9.0-alpine3.6
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test -v `go list ./... | grep -v /vendor/`

  # tag-revision:
  #   image: golang:1.9.0-alpine3.6
  #   commands:
  #   - apk --no-cache add git
  #   - git tag ${ESTAFETTE_BUILD_VERSION}
  #   - git push origin ${ESTAFETTE_BUILD_VERSION}
  #   when:
  #     status == 'succeeded' &&
  #     branch == 'master' &&
  #     server == 'gocd'

  set-build-status:
    image: extensions/github-status:dev
    when:
      server == 'estafette'

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(PiUCBMW1LEeyFk3i.vn0sEYGK_QU_tXtxQ7PbQra1L8a-reYGkDbzP9K9A6NzKbsf4CExtahJW7JjViXCtxuRlAt_c4kYF2oBRaCQ_4x3iDWLUp4P7AkchXI9Es4l7eeUWfB3A-Lpy4LG)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'