labels:
  app: estafette-ci-manifest
  team: estafette-team
  language: golang

pipelines:
  set-pending-build-status:
    image: extensions/github-status:beta
    status: pending
    when:
      server == 'estafette'

  build:
    image: golang:1.8.3-alpine3.6
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test -v `go list ./... | grep -v /vendor/`

  tag-revision:
    image: golang:1.8.3-alpine3.6
    commands:
    - apk --no-cache add git
    - git remote get-url origin
    - git tag ${ESTAFETTE_BUILD_VERSION}
    - git push origin ${ESTAFETTE_BUILD_VERSION}
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'gocd'

  set-build-status:
    image: extensions/github-status:beta
    when:
      server == 'estafette'

  slack-notify:
    image: golang:1.8.3-alpine3.6
    commands:
    - apk --update add curl
    - 'curl -X POST --data-urlencode ''payload={"channel": "#build-status", "username": "estafette-ci-builder", "text": "Build ''${ESTAFETTE_BUILD_VERSION}'' for ''${ESTAFETTE_LABEL_APP}'' has failed!"}'' ${ESTAFETTE_SLACK_WEBHOOK}'
    when:
      status == 'failed'