builder:
  track: dev

labels:
  app: estafette-ci-manifest
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 0
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending

  build:
    image: golang:1.10.2-alpine3.7
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - go test -v `go list ./... | grep -v /vendor/`

  tag-revision:
    image: golang:1.10.2-alpine3.7
    commands:
    - apk --no-cache add git
    - git tag ${ESTAFETTE_BUILD_VERSION}
    - git push origin ${ESTAFETTE_BUILD_VERSION}

  set-build-status:
    image: extensions/github-status:dev

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(PiUCBMW1LEeyFk3i.vn0sEYGK_QU_tXtxQ7PbQra1L8a-reYGkDbzP9K9A6NzKbsf4CExtahJW7JjViXCtxuRlAt_c4kYF2oBRaCQ_4x3iDWLUp4P7AkchXI9Es4l7eeUWfB3A-Lpy4LG)
    name: ${ESTAFETTE_LABEL_APP}
    channels:
    - '#build-status'
    when:
      status == 'failed'