# selects the dev track for builder in order to dogfood estafette's components
builder:
  track: dev

# these turn into ESTAFETTE_LABEL_... envvars, automatically injected into all pipeline steps
labels:
  app-group: estafette-ci
  type: library
  team: estafette
  language: golang

# generates a 0.0.x-<branch> version made available as ESTAFETTE_BUILD_VERSION envvar, automatically injected into all pipeline steps
version:
  semver:
    major: 0
    minor: 1
    releaseBranch: main

# global environments variables that are automatically injected into all pipeline steps and can be overridden by defining an envvar in a pipeline step with the same name
env:
  VAR1: somevalue
  VAR2: another value

# pipeline stages to be executed sequentially; for each step the 'when' is evaluated to see whether it should be executed or skipped
stages:
  build:
    image: golang:1.17-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...

  tag-revision:
    image: golang:1.17-alpine
    commands:
    - apk add git
    - git tag v${ESTAFETTE_BUILD_VERSION}
    - git push origin v${ESTAFETTE_BUILD_VERSION}

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'
