labels:
  app: estafette-ci-api
  team: estafette-team
  language: golang

# automatically executed stages on a push to the repository
# automatically executed stages on a push to the repository
stages:
  build:
    image: golang:1.12.1-alpine3.9
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOFLAGS: -mod=vendor
    commands:
    - go test ./...

bots:
  pr-bot:
    events:
    - bitbucket:pullrequest:created
    - bitbucket:pullrequest:updated
    - bitbucket:pullrequest:approved
    - bitbucket:pullrequest:unapproved
    - bitbucket:pullrequest:fulfilled
    - bitbucket:pullrequest:rejected
    - bitbucket:pullrequest:comment_created
    - bitbucket:pullrequest:comment_updated
    - bitbucket:pullrequest:comment_deleted
    stages:
      welcome:
        image: extensions/github-pr-bot:stable

  any-bot:
    events:
    - bitbucket:repo:push
    - bitbucket:repo:fork
    - bitbucket:repo:transfer
    - bitbucket:repo:created
    - bitbucket:repo:deleted
    - bitbucket:repo:commit_comment_created
    - bitbucket:repo:commit_status_created
    - bitbucket:repo:commit_status_updated
    - bitbucket:issue:created
    - bitbucket:issue:updated
    - bitbucket:issue:comment_created
    - bitbucket:pullrequest:created
    - bitbucket:pullrequest:updated
    - bitbucket:pullrequest:approved
    - bitbucket:pullrequest:unapproved
    - bitbucket:pullrequest:fulfilled
    - bitbucket:pullrequest:rejected
    - bitbucket:pullrequest:comment_created
    - bitbucket:pullrequest:comment_updated
    - bitbucket:pullrequest:comment_deleted
    - github:commit_comment
    - github:create
    - github:delete
    - github:deployment
    - github:deployment_status
    - github:fork
    - github:gollum
    - github:installation
    - github:installation_repositories
    - github:issue_comment
    - github:issues
    - github:label
    - github:marketplace_purchase
    - github:member
    - github:membership
    - github:milestone
    - github:organization
    - github:org_block
    - github:page_build
    - github:project_card
    - github:project_column
    - github:project
    - github:public
    - github:pull_request_review_comment
    - github:pull_request_review
    - github:pull_request
    - github:push
    - github:release
    - github:repository
    - github:status
    - github:team
    - github:team_add
    - github:watch
    - github:integration_installation_repositories
    stages:
      backup:
        image: extensions/backup-event:stable

  stale-issues-bot:
    triggers:
    - cron: 
        schedule: '0 10 * * *'
    clone: true
    stages:
      welcome:
        image: extensions/github-stale-issue-bot:stable